Add ConnectedServer Property to AprsIsClient
CBielstein/APRSsharp pull request #134
Opened 2022-05-30 22:43 UTC by martelro

## Description

As described in #120, a rotating address is often used to connect to an APRS-IS server; however, the actual connected server is not known to the user.

This change adds parsing to the AprsIsClient class to obtain the connected server and expose it as a property of the class.

## Changes

- Add nullable public property, ConnectedServer, to AprsIsClient
- Add parsing logic via private method to obtain the server name from the connected server's login response and assign to ConnectedServer.  If server name cannot be determined, the property value is set to null.
- Private method also logs server name

## Validation

- Build passes
- Created and passed unit tests
- Ran locally at LogInformation visibility level to confirm server name is captured in property

2022-06-01 04:22 UTC, CBielstein requested changes
This looks really great! Clearly you know your way around the C# stack more than the descriptions gave you credit for. No offense intended there, just never know the experience level and want to be welcoming to newbies as well. 😊

Just caught the one race condition, which I only caught as my PC for some reason fails on it 100% of the time. I wouldn't have seen it otherwise. There are also a few line of test code that came over from the other test but aren't necessary here that we can clean up.

Overall, looks fantastic (especially in a bit of a messy code base like ours 😁)! Please make the little tweaks and I'm excited to merge this in!

2022-06-01 04:22 UTC, CBielstein commented on test/AprsIsClientUnitTests/ReceiveUnitTests.cs
> +            };
Unless I'm missing something (always possible), I think we can delete this and the `tcpMessagesReceived` and `stateChangesReceived` lists up top of this test. We use them in the other test to assert messages were handled appropriately, but since we correctly aren't asserting that here then we don't have to actually handle messages here.

2022-06-01 04:22 UTC, CBielstein commented on src/AprsIsClient/AprsIsClient.cs
> +        private void SetConnectedServer(string? loginResponse)
Super thorough code, thank you! 😊

2022-06-01 04:22 UTC, CBielstein commented on src/AprsIsClient/AprsIsClient.cs
> +                                    SetConnectedServer(received);
Really interesting one, but this seems to be triggering a race condition that (for some reason), only my computer is hitting. Looks clean in the cloud, I'm willing to bet clean on your machine, fails almost 100% of the time on mine.

After investigating a bit, the race condition is that the test waits for `State` to change, then reads the server name. But the code here (in a different task) also _sets_ the server after `State` changes. If we switch this so that `SetConnectedServer` happens before assigning `State`, then the race condition is removed and we're assured to see the updated value of `ConnectedServer` once `State` changes.

Important for whatever reason my machine fails here, but also important as the change to `State` raises an event, so we want any code subscribing to the event to see the correct value as well.

2022-06-01 23:48 UTC, martelro commented on test/AprsIsClientUnitTests/ReceiveUnitTests.cs
> +            };
Makes sense.  Removed!

2022-06-01 23:49 UTC, martelro commented on src/AprsIsClient/AprsIsClient.cs
> +                                    SetConnectedServer(received);
That is interesting.  As you stated, I did not see that on this end.  Either way, I flipped the statements so this should no longer be an issue.

2022-06-01 23:50 UTC, martelro commented
Thank you for the kind review.  Admittedly, I know some areas of C# better than others, but those will come with time and practice I hope!

I've pushed the updates, but please let me know if there's anything else.  Thank you!

2022-06-02 06:32 UTC, CBielstein approved these changes
Perfect! Thanks for the updates and the code in general! You're more than welcome to code with us whenever you'd like! 😎

2022-06-02 06:34 UTC, CBielstein commented
Commenting for my own sake: I _did_ rerun the build task due to test timeout failures, but these were not related to this test. They are a known issue of our parallelism and such issues would be resolved by #125. With that in mind, I'm still merging this PR and we can fix #125 asap to ensure this doesn't happen again.

2022-06-02 06:37 UTC, merged