console app executable
CBielstein/APRSsharp pull request #49
Opened 2020-11-11 18:38 UTC by eddywine

## Description

Adding a console app executable for the project 

## Changes

- Changes in the console app project file
- Changes in the src directory where the executable has been stored

## Validation

* _Bullet points listing validation steps (e.g. manual testing, test passes, etc.)_

2020-11-13 04:53 UTC, CBielstein requested changes
Moving in the right direction. Let's avoid submitting binaries (see my comments in the files) and a few other bits of feedback. Thanks!

2020-11-13 04:53 UTC, CBielstein commented on src/ConsoleApplication/ConsoleApplication.csproj
> +    <PublishTrimmed>false</PublishTrimmed>
This is false by default, so the line can be omitted.

2020-11-13 04:53 UTC, CBielstein commented on src/ConsoleApplication/ConsoleApplication.csproj
> +    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
Although I suggested `win-x64`, perhaps let's target `win-x86` for more compatibility? I'm not sure how much of a difference this makes these days, to be honest.

2020-11-13 04:53 UTC, CBielstein commented on src/ConsoleApplication/ConsoleApplication.csproj
>    <PropertyGroup>
Although I understand the desire to make the executable easy to access, we should avoid checking in compiled files (.exe and .pdb in this PR). These files would have to be updated on every single commit and fall out of sync on any code change. From experience, this is a pretty big pain. The Windows team refers to such submitted files as [FCIBs](https://devblogs.microsoft.com/oldnewthing/20171114-00/?p=97396), which has both a business-acceptable version and well...the real version.

Instead of checking in binaries to code, this is where continuous deployment comes in to some other destination (usually a web server of some kind). As discussed, this is a reasonable goal...once I set up somewhere for us to host this. 😅 

Recall that most people who are in a code repository are developers, so building is not a difficult request to make. We should document the build command in the readme file, which should be sufficient for this PR.

2020-11-13 04:53 UTC, CBielstein commented on src/ConsoleApplication/ConsoleApplication.csproj
> +    <PublishSingleFile>true</PublishSingleFile>
We should also rename this to a less generic name. `ConsoleApplication` is a good name for a project inside the code as it has enough context in the code repository. However, I don't want to type `> ConsoleApplication.exe` to see APRS packets. Maybe `> APRSsharp` or something is better. Check out [AssemblyName](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019), which I believe does what we want.

2020-11-22 16:24 UTC, MONIMAKER365 commented
up for grabs

2020-11-24 10:14 UTC, MONIMAKER365 approved these changes
great work

2020-11-30 06:00 UTC, CBielstein commented
Closing in favor of #51

2020-11-30 06:00 UTC, closed without merging