Injection pr
CBielstein/APRSsharp pull request #59
Opened 2020-12-24 12:03 UTC by eddywine

## Description

A PR that implements disposable methods and injection methods and can help in the mocking process since the mocking can be done on the interface. Separates the TCP connection and APRS-IS connection codes

## Changes

* Injection code for the ITCpconnection
* Interface for ITCpconnection 
* Implementing disposable method for the code

## Validation

* Test cases passing

2020-12-27 05:09 UTC, CBielstein requested changes

2020-12-27 05:09 UTC, CBielstein commented on src/AprsISLibrary/TcpConnection.cs
> +            tcpClient.Connect(@server, 14580);
I think this should reference the port passed in by the caller, right?

```suggestion
            tcpClient.Connect(server, port);
```

2020-12-27 05:09 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +        }
This comment says optional...but this seems mandatory to me. If `tcpConnection` is `null`, then none of the rest of the code will work, right?

I think we should go ahead and remove the "optional" word from the comment and add a null check (throw new argument null exception if tcpConnection is null, see other places in the code for null check syntax).

2020-12-27 22:50 UTC, eddywine commented on src/AprsISLibrary/AprsIsConnection.cs
> +        }
I have made the changes and will be waiting for your review so that I do the MOCK then we can go through it on Tuesday

2020-12-28 06:24 UTC, CBielstein requested changes
Functionally, it looks great. Just a few documentation and style tweaks and this will be good to go!

2020-12-28 06:24 UTC, CBielstein commented on src/AprsISLibrary/TcpConnection.cs
> +            tcpClient.Connect(@server, port);
`server` here is prefixed with `@`, which I believe is unnecessary...

Prefixing a variable name with `@` is a way to [allow a C# keyword to be used as a variable](https://stackoverflow.com/questions/429529/what-does-the-symbol-before-a-variable-name-mean-in-c). Since "server" doesn't appear to be a [C# keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/), I think we should be safe to remove it.

```suggestion
            tcpClient.Connect(server, port);
```

2020-12-28 06:24 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +        /// <param name="tcpConnection">A TcpConnection to use for communication.</param>
Found another correction here. This should really say it's an `ITcpConnection` rather than just `TcpConnection` we as are allowing the abstraction of the interface here.

Also, we can reference types in the XML comments here, which is pretty cool. It allows the editor (such as VS Code) to show more detailed information in the auto completion tooltips. See above where I used the `<see cref="AprsIsConnection"/>` element, that will show up a link to the `AprsIsConnection` documentation. More importantly, this will cause the compiler to check if the type exists. If it doesn't, an error will be raised. This ensures that if a type name changes, we cannot forget to update it in the comments about it. This is a similar motivation to the use of `nameof` which I mentioned in another comment.

```suggestion
        /// <param name="tcpConnection">An <see cref="ITcpConnection"/> to use for communication.</param>
```

2020-12-28 06:24 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +                throw new ArgumentNullException();
Minor tweak here while you're making the other adjustments: it's considered best practice for `ArgumentNullException` to specify the name of the parameter that it's checking. Doing so changes the error from something generic like "an argument cannot be null" to include the name e.g. "tcpConnection cannot be null," which is easier to debug. FxCop will eventually enforce this rule once I enable FxCop everywhere so that we'll be reminded of it automatically.

To do this, `ArgumentNullException` has a [constructor](https://docs.microsoft.com/en-us/dotnet/api/system.argumentnullexception.-ctor?view=netcore-3.1#System_ArgumentNullException__ctor_System_String_) that allows passing the name of the argument in question. It's easy to pass the name in quotes (e.g. `"tcpConnction"`) but this can be a pain if the argument changes names as we will have to remember to change it here as well...

Fortunately, C# has this nifty built-in function called [`nameof`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof) that takes in a variable, type, property, etc. and returns the coded name of that variable. This means we are referencing the variable, which means the compiler will help enforce a rename, etc.

```suggestion
                throw new ArgumentNullException(nameof(tcpConnection));
```

2020-12-29 18:33 UTC, CBielstein approved these changes
Great work!

2020-12-29 18:35 UTC, merged