'cancella'
CBielstein/APRSsharp pull request #76
Opened 2021-03-10 17:12 UTC by eddywine

## Description

_A brief description of the PR including motivation and strategy._

## Changes

* _Bullet points describing specific changes in this PR_

## Validation

* _Bullet points listing validation steps (e.g. manual testing, test passes, etc.)_

2021-03-23 05:15 UTC, CBielstein requested changes
On the right track! Just a few little tweaks and this is good to go.

2021-03-23 05:15 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +            bool stopReceive = true;
This is on the right track. Two things you should adjust here and I think you've got it.

1. `bool stopReceive = true;` is a _local_ variable in the scope of the `Disconnect()` method. That means this method creates a new variable called `stopReceive`, sets it equal to `true`, and then exits. When the method exists, this local method's `stopReceive` is destroyed. Since it is declared separately from the `bool stopReceive` in `Receive(...)`, these two values are not linked and won't change each other. Fortunately, the logic is right aside from that. So if you declare `private bool stopReceive;` on the _class_ by declaring it in the class but outside of methods (for reference, `private readonly ITcpConnection tcpConnection;` declares a variable named `tcpConnection` on the class as it isn't in a method), then you can set and access that `stopReceive` without redeclaring it (so no need for the `bool` declaration in front of it, when you specify a type then a name, that creates a _new_ variable, so just use the name to get to the existing one). If that doesn't quite make sense, this might be a helpful read on variable scoping in C# and object oriented programming: https://www.geeksforgeeks.org/scope-of-variables-in-c-sharp

2021-03-23 05:15 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +            bool stopReceive = true;
I put my second note in a different comment for easier thread conversation. Read on down below!

2021-03-23 05:15 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +            bool stopReceive = false;
The second note:

2. You are absolutely doing the correct logic on setting `stopReceive` to the right values at the right times. However, this PR doesn't appear to read it back. The giant `while` loop down below is where we do all of our receiving. However, `while(true)` is what we call an infinite loop: it will _never_ stop because we put a constant value (`true`) as the condition. Instead, we want to be able to break the loop when `stopReceive` is changed, so we should change the value inside the `while ( ... )` condition such that it is based on `stopReceive` and will in fact break out of the loop when you set `stopReceive = true;` in `Disconnect();`

2021-03-23 06:03 UTC, CBielstein commented on test/AprsIsConnectionUnitTests/AprsIsConnectionUnitTests.cs
> +        public void TestDisconnect()
I wrote a test to help you verify this. My little way of saying "sorry I took two weeks to review this." 😄 

This does all sorts of fun stuff with mocks and async. Feel free to ask questions if it's not clear what's happening here.

2021-04-13 02:03 UTC, CBielstein requested changes
Getting closer. A few more changes needed before this is functionally correct.

Also, please update the title and description of the PR. It helps us both now and later. Now as we finalize the change, we can keep track of what this code is supposed to do and how it was tested. Later it helps us if we have to review WHY changes are made when tracking a bug or something, it's immensely helpful to know why code was changed and how it was tested at the time.

2021-04-13 02:03 UTC, CBielstein commented on src/AprsISLibrary/TcpConnection.cs
> +      }
This method is in the right spot but it needs to actually close the TCP connection, else it is meaningless to call it. Check out [`TcpClient.Close`](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.close?view=netcore-3.1) for a pointer in the right direction.

2021-04-19 02:39 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +                while (stopReceive == false)
Don't forget to set `stopReceive = false` in the `Receive()` method before we get here.

Consider the scenario where we write the following code. I could see this happening if/when an app is built with this code and a user starts and stops connections.

```csharp
var aprsIs = new AprsIsConnection(); // stopReceive is false by default
aprsIs.Receive(); // stopReceive is false, so we begin receiving

// Some user actions, etc.

aprsIs.Disconnect(); // stopReceive is set to true, so we stop receiving

// Some user actions, etc.

aprsIs.Receive(); // stopReceive is true, so we do not receive anything.
```

2021-04-19 02:39 UTC, CBielstein commented on src/APRSsharp/Program.cs
> +            }
This logic is absolutely correct. I'll recommend a tweak to make it more concise and avoid repeating the `input = Console.ReadKey();` line. When possible, we want to avoid repeating code. If there happens to be a bug in the code or the functionality needs to change, the developer implementing the fix may miss the second or third place the code is duplicated.

In this case, we can take advantage of a `while (true)` _always_ executing the first time and just put our `ReadKey` call at the top of the loop and any actions we take on it lower down.

```suggestion
            while (true)
            {
                ConsoleKeyInfo input = Console.ReadKey();

                if (input.Key == ConsoleKey.Q)
                {
                    n.Disconnect();
                    await receive;
                    break;
                }
            }
```

2022-03-12 05:49 UTC, CBielstein requested changes
Looking good! Just one more tweak to ensure functionality then a few stylistic changes. Check back to the conversation tab to ensure you're taking feedback from the open threads!

2022-03-12 05:49 UTC, CBielstein commented on AprsSharp.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "AprsIsConnectionUnitTests", "test\AprsIsConnectionUnitTests\AprsIsConnectionUnitTests.csproj", "{1188140D-59F2-4BA0-9914-122DEDD3035D}"
Was this an intentional change? Might be worth reverting these changes to the solution. You can run `git checkout main -- AprsSharp.sln` to check out the solution file exactly as it is in the main branch. In general, it's good practice to only change the minimum number of files and lines in a PR. This prevents us from accidentally breaking something else.

2022-03-12 05:49 UTC, CBielstein commented on src/AprsIsConnection/AprsIsConnection.cs
> +        private bool stopReceive;
Personal preference, but can we invert the logic here? Since it's `stopReceive` but we're really using it to check if we should continue receiving, we have to negate. If we switch it to `private bool receiving` or something, then we don't have to negate it lower down, it can just be `while (receiving)`, which is easier to read and think about.

2022-03-12 05:49 UTC, CBielstein commented on test/AprsIsConnectionUnitTests/AprsIsConnectionUnitTests.cs
> +            Task receiveTask = connection.Receive(null, null, null, null);
These failures are coming up because the first three arguments of `Receive` cannot be null. They must be instances of a string. This kind of non-null type enforcement helps create a bit more safety in the program by eliminating lots of null reference exceptions which would cause the program to crash.

2022-03-12 05:49 UTC, CBielstein commented on src/APRSsharp/Program.cs
> +                if (user_input.Key == ConsoleKey.Q)
I suspect this only checks against upper-case Q. Does it work on lower-case as well or do we need to explicitly compare against that?

2022-03-12 07:10 UTC, eddywine commented on src/APRSsharp/Program.cs
> +                if (user_input.Key == ConsoleKey.Q)
Yes, it accepts both lower case q and upper case Q. I have been testing with the two.  Console.ReadKey() have some enum of upper cases so if you type say small letter q, it will be interpreted as Q. The behavior of getting the exact letter typed whether lower or upper case can be implemented by changing it to Console.Read() which will get the exact value

2022-03-12 07:12 UTC, CBielstein commented on src/APRSsharp/Program.cs
> +                if (user_input.Key == ConsoleKey.Q)
Oh, cool. Okay, that works for me!

2022-03-12 08:32 UTC, eddywine commented on AprsSharp.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "AprsIsConnectionUnitTests", "test\AprsIsConnectionUnitTests\AprsIsConnectionUnitTests.csproj", "{1188140D-59F2-4BA0-9914-122DEDD3035D}"
I was having two project files thus having some errors so I decided to remove all of them and added a solution file again. But I can revert to avoid any break in functionality

2022-03-15 03:38 UTC, CBielstein commented on test/AprsIsConnectionUnitTests/AprsIsConnectionUnitTests.csproj
> +    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.0">
This package is [marked as deprecated](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/). Let's not add it here. If we need to improve our static analysis, there are other ways to do so that will work across the full repository instead of just this project.

2022-03-15 03:38 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +                while (stopReceive == false)
Still not quite right here. We need the start, stop, restart case. To handle that, you need to re-set `receiving` to true in the beginning of `Receive`.

2022-03-15 03:39 UTC, CBielstein requested changes
Looking really good. Just a few minor tweaks!

2022-04-17 00:05 UTC, CBielstein commented on src/AprsISLibrary/AprsIsConnection.cs
> +                while (stopReceive == false)
We discussed this offline, but I was wrong. `TcpClient` doesn't allow re-creating the connection, so we can't either at the current design of `AprsIsConnection`. Let's just stick with single connection per instance to match `TcpClient`, so how you had it was right. Sorry!

2022-04-17 00:12 UTC, CBielstein approved these changes
This looks ready to go! I see that test failing in CI...but it's running just fine on my local machine. I suspect it's a threading issue on the Actions runners. We'll need to solve the flaky tests in the long run, but it doesn't need to be part of this PR. For now, just in crease that 2000 ms timeout to 5000 ms or something. That should let it pass and then you're good to merge!

2022-04-21 04:21 UTC, merged